name: Acción para Rama 1

on:
  push:
    branches:
      - test_1

jobs:
  print-messages:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout del repositorio
        uses: actions/checkout@v3

      - name: Imprimir mensajes en la consola para Rama 1
        run: 
          echo "Rama 1  Print 1"
          echo "Rama 1  Print 2"
          echo "Rama 1  Print 3"